# para limpiar cache desde ruta (temporal)
clear_cache:
    path: /clear-cache
    controller: App\Controller\CacheController::clearCache

# rutas
index:
    path: /
    controller: App\Controller\ProviderController::index

create:
    path: crear
    controller: App\Controller\ProviderController::create