# para limpiar cache desde ruta (temporal)
clear_cache:
    path: /clear-cache
    controller: App\Controller\CacheController::clearCache

# rutas
proveedor.index:
    path: /
    controller: App\Controller\ProviderController::index

proveedor.create:
    path: /proveedores/crear
    controller: App\Controller\ProviderController::create

proveedor.store:
    path: /proveedores/guardar
    controller: App\Controller\ProviderController::store

proveedor.show:
    path: /proveedores/{id}
    controller: App\Controller\ProviderController::show

proveedor.update:
    path: /proveedores/{id}/actualizar
    controller: App\Controller\ProviderController::update

proveedor.destroy:
    path: /proveedores/{id}/eliminar
    controller: App\Controller\ProviderController::destroy
    methods: [DELETE]


