# para limpiar cache desde ruta (temporal)
clear_cache:
    path: /clear-cache
    controller: App\Controller\CacheController::clearCache

# rutas
index:
    path: /
    controller: App\Controller\ProviderController::index

create:
    path: /proveedores/crear
    controller: App\Controller\ProviderController::create

show:
    path: /proveedores/{proveedor}
    controller: App\Controller\ProviderController::show
    defaults: {proveedor: 'proveedor nulo'}
    methods: [GET]
    requirements:
      proveedor: \w

#delete:
eliminar.proveedor:
    path: /proveedores/eliminar/{id?}
    controller: App\Controller\ProviderController::destroy
    methods: [DELETE]
    defaults: {id: 1}
